rootProject.name = 'NeoForbric'
include 'loader', 'fixtures:game', 'fixtures:mod-a', 'fixtures:mod-b', 'fixtures:mod-c'
include 'probes:fabric-item'
include 'probes:fabric-client'
include 'client-ui'
include 'installer'
include 'neoforge-runtime'
include 'forge-runtime'
include 'probes:neoforge-registry'
