dependencies {
    compileOnly "net.fabricmc:fabric-loader:${rootProject.fabricLoaderVersion}@jar"
    compileOnly files(rootProject.layout.buildDirectory.file('minecraft/server-mojang.jar'))
    compileOnly fileTree(rootProject.layout.buildDirectory.dir('minecraft/libraries')) { include '*.jar' }
}
tasks.named('compileJava') { dependsOn ':prepareMinecraft' }
tasks.register('remapJar', JavaExec) {
    dependsOn tasks.named('jar'), ':prepareMinecraft'
    javaLauncher = javaToolchains.launcherFor { languageVersion = JavaLanguageVersion.of(21) }
    classpath = project(':loader').sourceSets.main.runtimeClasspath
    mainClass = 'org.neoforbric.minecraft.GamePreparation'
    maxHeapSize = '2g'
    args 'remap-probe', rootProject.layout.buildDirectory.dir('minecraft').get().asFile.absolutePath,
            tasks.named('jar').get().archiveFile.get().asFile.absolutePath,
            layout.buildDirectory.file('libs/fabric-item-intermediary.jar').get().asFile.absolutePath
}
