dependencies {
    compileOnly files(rootProject.layout.buildDirectory.file('forge-client/client-forge.jar'))
    compileOnly fileTree(rootProject.layout.buildDirectory.dir('forge-client/libraries')) { include '**/*.jar'; exclude 'org/ow2/asm/**' }
    compileOnly fileTree(rootProject.layout.buildDirectory.dir('minecraft-client/libraries')) { include '*.jar' }
}
tasks.named('compileJava') { dependsOn ':prepareForgeClient' }
tasks.named('jar') { manifest { attributes('MixinConfigs': 'nf-forge-probe.mixins.json') } }
